# Generated by Django 4.2.4 on 2024-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="projects.tag"),
        ),
    ]
